import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.slow()
  await page.goto('https://miq-nrw.vercel.app/de');
  await page.locator('div').filter({ hasText: /^Vorfall melden$/ }).getByRole('link').click();
  await page.getByRole('button', { name: 'Los geht’s' }).click();
  await page.getByLabel('Eine andere Person').check();
  await page.getByLabel('Ich melde in Vertretung für die betroffene Person').check();
  await page.locator('div').filter({ hasText: /^Weiter$/ }).first().click();
  await page.getByPlaceholder('Bitte beschreibe den Vorfall so genau wie möglich.').click();
  await page.getByPlaceholder('Bitte beschreibe den Vorfall so genau wie möglich.').fill('ls;kdjdlm lsadjkdkdfllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll');
  await page.getByRole('button', { name: 'Weiter' }).click();
  await page.getByRole('gridcell', { name: '17' }).click();
  await page.getByLabel('Es ist über einen längeren Zeitraum passiert.').check();
  await page.getByLabel('', { exact: true }).fill('15/02/2020 - 17/02/2021');
  await page.locator('div').filter({ hasText: /^Weiter$/ }).first().click();
  await page.locator('#place').check();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('ghana');
  await page.locator('div').filter({ hasText: /^Weiter$/ }).first().click();
  await page.getByLabel('Sexuelle Orientierung').check();
  await page.getByLabel('Anderes, und zwar').check();
  await page.getByRole('textbox').fill('hello there');
  await page.locator('div').filter({ hasText: /^Weiter$/ }).first().click();
  await page.getByLabel('Schwulenfeindlichkeit').check();
  await page.getByLabel('Anderes, und zwar').check();
  await page.getByRole('textbox').fill('hello there ');
  await page.locator('div').filter({ hasText: /^Weiter$/ }).first().click();
  await page.getByLabel('Ja, und zwar:').check();
  await page.getByLabel('Anti-Schwarzer Rassismus').check();
  await page.locator('div').filter({ hasText: /^Weiter$/ }).first().click();
  await page.getByLabel('agendar').check();
  await page.getByLabel('männlich').check();
  await page.locator('#gender8').check();
  await page.getByRole('textbox').fill('hello');
  await page.getByLabel('lesbisch').check();
  await page.getByLabel('homoromantisch').check();
  await page.getByLabel('unter 18 Jahre').check();
  await page.getByLabel('Ich willige ein, dass meine Eingaben im Falle von Mehrfachdiskriminierung anonymisiert mit den zuständigen Meldestellen (Hyperlink zu Auflistung) geteilt werden.').check();
  await page.getByLabel('Hiermit bestätige ich die Richtigkeit meiner Angaben, die Kenntnisnahme der Datenschutzbestimmungen (Hyperlink Datenschutzkonzept) und dass ich den darin beschriebenen Verarbeitungen meiner personenbezogenen Daten zustimme.*').check();
  await page.locator('div').filter({ hasText: /^Meldung abschicken$/ }).first().click();
  await page.getByRole('button', { name: 'Verweisberatung' }).click();
});